name: Metadata

on:
  push:
    branches:
      - main
    paths:
      - metadata.json
  workflow_dispatch:

permissions: {}

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - id: metadata
        run: |
          json=$(cat metadata.json | jq -c)
          echo "json=${json}" >> "$GITHUB_OUTPUT"
      - uses: snow-actions/nostr@v1.7.0
        with:
          kind: 0
          content: ${{ steps.metadata.outputs.json }}
          relays: ${{ vars.NOSTR_RELAYS }}
          private-key: ${{ secrets.NOSTR_NSEC }}
